### ISSUE TITLE
Travis-CI build fails on linting

### ISSUE THREAD

**Issue by coruus** [yahoo/end-to-end#27]
The Travis-CI build fails on the after_script linting. Because there are so many lint errors that Travis eventually times out.

Possible Travis bug: Should timing out in an after_script action fail a build?

**Comment by diracdeltas** [comment]
I'm going to try to fix enough lint errors (indentation, etc.) that Travis at least stops timing out

**Comment by diracdeltas** [comment]
Actually, I suspect it's timing out on `wordlist.js` because 2^16 lines is a lot or something. That should be excluded from linting anyway.
