### ISSUE TITLE
@expose annotation is deprecated in closure-compiler

### ISSUE THREAD

**Issue by taravancil** [yahoo/end-to-end#41]
`@expose` is deprecated and should be replaced by `@nocollapse` or `@export`.

Here's [a discussion](https://groups.google.com/forum/#!msg/closure-compiler-discuss/pZaodHd0KD0/VA8yHNqWtckJ) about the motivation for deprecating `@expose`.

`download-libs.sh` installs the compiler from [https://github.com/google/closure-compiler](), which marks `@expose` as deprecated. Until this is fixed you can avoid the build errors by downloading an older release of the compiler from [here](https://github.com/google/closure-compiler/wiki/Binary-Downloads). The most recent release works fine.

**Comment by diracdeltas** [comment]
thanks, assigning to myself so i don't forget to fix this soon

**Comment by diracdeltas** [comment]
@taravancil This dropped off my radar last week; feel free to open pull requests for any build issues you encounter.

**Comment by diracdeltas** [comment]
This seems to have been fixed with #46

**Comment by koto** [comment]
FYI this will be fixed upstream soon.
