### ISSUE TITLE
keyserver client: retry updates after network failures

### ISSUE THREAD

**Issue by andres-erbsen** [yahoo/end-to-end#67]
If we want to avoid the need for manual recovery in case a profile update makes it to the keyserver but the reply does not make it back, the client should retry the update until it gets a definitive response. Not doing this can cause the affected client to sign messages using the previous PGP key while its contacts see the results of an update whose reply got list (and thus they reject the signatures).

**Comment by adon-at-work** [comment]
merged with #68
