### ISSUE TITLE
build_extension-error-message

### ISSUE THREAD

**Issue by sitSearcher** [yahoo/end-to-end#7]
Hey there,

I tested googles-end-to-end and today I wanted to test yours, but when I try to build extension (./do.sh build_extension) there is a bug. There is always a message, saiing, "Download libraries needed to build first. Use ./do.sh install_deps". I did it!.

But when I do ./do.sh install_deps there is always an error:
"./download-libs.sh: 30: ./download-libs.sh: svn: not found"

Is there somebody who can fix it please? Or can tell me, how I can solve the problem?

Thanks a lot.

**Comment by diracdeltas** [comment]
Hi there, for now you can just install SVN: `sudo apt-get install subversion` on linux or `brew install subversion` on osx. I'm not sure why SVN is needed or if it is anymore; will look into it.

**Comment by koto** [comment]
Yan, we dropped SVN requirement here - https://github.com/google/end-to-end/commit/3a2fe0a3f816bb32dc95e9addd4322d84116edae

**Comment by diracdeltas** [comment]
Thank you @koto! We have a Google rebase branch that has that change, I think. Should be ported to OSS soon.

**Comment by sitSearcher** [comment]
Thanks

**Comment by diracdeltas** [comment]
Actually `download-libs.sh` in our fork doesn't call `svn` anymore either. @sitSearcher, what commit did you build from?

**Comment by sitSearcher** [comment]
Hey diracdeltas,

I tested it again. The same problem. I did the "Setup" followed by end-to-end/docs/README.build :

The single steps:
  git clone https://code.google.com/p/end-to-end.build/
  cd end-to-end.build/
  ./do.sh install_deps
  ./do.sh build_extension

While doing "./do.sh install_deps" the following error:
"./download-libs.sh: 30: ./download-libs.sh: svn: not found"

After that triing "./do.sh build_extension" produced the following error:
"Download libraries needed to build first. Use ./do.sh install_deps."

I had a look at koto´s post and updated your "do.sh" and your "download-libs.sh" (i got from "git clone https://code.google.com/p/end-to-end.build/") as in koto´s post and it works fine.

**Comment by koto** [comment]
Oh, you're using deprecated build instructions. end-to-end.build repository is not the right one. Use build instructions from: 

https://github.com/yahoo/end-to-end/blob/master/README.markdown

**Comment by diracdeltas** [comment]
What koto said. I'll fix the deprecated instructions.

**Comment by sitSearcher** [comment]
Hey you two,

ok, thanks, but where is the "instructions" I can follow on this url? 
"Install prerequisites" --> ok, installed.
"Build the extension" --> ?
Do I really need to build a keyserver on my own?! If so, how?!?
Or can I use it (like googles-end-to-end) without one?!

Actually I did:
git clone https://github.com/yahoo/end-to-end/
cd end-to-end
./do.sh install_deps
./do.sh build_extension_debug

Is this the right way? I think not, because I get an error while trying to "Make key" ("Oops, faild to send keys to the keyserver. Are you on the corp network and logged into Bouncer?"). I think it is really necessary to build an own keyserver?! If so, I think I have to wait unless you have an guide?!

Thanks

**Comment by diracdeltas** [comment]
Yeah, see note in README about keyserver. We'll probably release a keyserver component that you can run locally this week.

**Comment by diracdeltas** [comment]
I fixed the outdated README.build, and #4 is the issue tracking the open source keyserver component.
